CREATE TABLE [dbo].[Client] (
    [DCLink]                   INT             IDENTITY (1, 1) NOT NULL,
    [Account]                  VARCHAR (20)    NULL,
    [Name]                     VARCHAR (50)    NULL,
    [Title]                    VARCHAR (5)     NULL,
    [PriceHalf]                DECIMAL (18, 2) CONSTRAINT [DF_Client_PriceHalf] DEFAULT ((0)) NOT NULL,
    [Init]                     VARCHAR (6)     NULL,
    [Contact_Person]           VARCHAR (30)    NULL,
    [Physical1]                VARCHAR (40)    NULL,
    [Physical2]                VARCHAR (40)    NULL,
    [Physical3]                VARCHAR (40)    NULL,
    [Physical4]                VARCHAR (40)    NULL,
    [Physical5]                VARCHAR (40)    NULL,
    [PhysicalPC]               VARCHAR (15)    NULL,
    [Addressee]                VARCHAR (30)    NULL,
    [Post1]                    VARCHAR (40)    NULL,
    [Post2]                    VARCHAR (40)    NULL,
    [Post3]                    VARCHAR (40)    NULL,
    [Post4]                    VARCHAR (40)    NULL,
    [Post5]                    VARCHAR (40)    NULL,
    [PostPC]                   VARCHAR (15)    NULL,
    [Delivered_To]             VARCHAR (30)    NULL,
    [Telephone]                VARCHAR (25)    NULL,
    [Telephone2]               VARCHAR (25)    NULL,
    [Fax1]                     VARCHAR (25)    NULL,
    [Fax2]                     VARCHAR (25)    NULL,
    [AccountTerms]             INT             NULL,
    [CT]                       BIT             CONSTRAINT [DF__CLIENT__CT__6C390A4C] DEFAULT ((0)) NOT NULL,
    [Tax_Number]               VARCHAR (15)    NULL,
    [Registration]             VARCHAR (20)    NULL,
    [Credit_Limit]             FLOAT (53)      NULL,
    [RepID]                    INT             NULL,
    [Interest_Rate]            FLOAT (53)      NULL,
    [Discount]                 FLOAT (53)      NULL,
    [On_Hold]                  BIT             CONSTRAINT [DF__CLIENT__On_Hold__6D2D2E85] DEFAULT ((0)) NOT NULL,
    [BFOpenType]               INT             NULL,
    [EMail]                    VARCHAR (60)    NULL,
    [BankLink]                 INT             NULL,
    [BranchCode]               VARCHAR (30)    NULL,
    [BankAccNum]               VARCHAR (30)    NULL,
    [BankAccType]              VARCHAR (30)    NULL,
    [AutoDisc]                 FLOAT (53)      NULL,
    [DiscMtrxRow]              INT             NULL,
    [MainAccLink]              INT             NULL,
    [CashDebtor]               BIT             CONSTRAINT [DF__CLIENT__CashDebt__6E2152BE] DEFAULT ((0)) NOT NULL,
    [DCBalance]                FLOAT (53)      NULL,
    [CheckTerms]               BIT             CONSTRAINT [DF__CLIENT__CheckTer__6F1576F7] DEFAULT ((0)) NOT NULL,
    [UseEmail]                 BIT             CONSTRAINT [DF__CLIENT__UseEmail__70099B30] DEFAULT ((0)) NOT NULL,
    [iIncidentTypeID]          INT             NULL,
    [iBusTypeID]               INT             NULL,
    [iBusClassID]              INT             NULL,
    [iCountryID]               INT             NULL,
    [iAgentID]                 INT             NULL,
    [dTimeStamp]               DATETIME        NULL,
    [cAccDescription]          VARCHAR (80)    NULL,
    [cWebPage]                 VARCHAR (50)    NULL,
    [iClassID]                 INT             NULL,
    [iAreasID]                 INT             NULL,
    [cBankRefNr]               VARCHAR (30)    NULL,
    [iCurrencyID]              INT             NULL,
    [bStatPrint]               BIT             CONSTRAINT [DF_Client_bStatPrint] DEFAULT ((0)) NOT NULL,
    [bStatEmail]               BIT             CONSTRAINT [DF_Client_bStatEmail] DEFAULT ((0)) NOT NULL,
    [cStatEmailPass]           VARCHAR (20)    NULL,
    [bForCurAcc]               BIT             CONSTRAINT [DF_Client_bForCurAcc] DEFAULT ((0)) NOT NULL,
    [fForeignBalance]          FLOAT (53)      NULL,
    [bTaxPrompt]               BIT             CONSTRAINT [DF_Client_bTaxPrompt] DEFAULT ((1)) NOT NULL,
    [iARPriceListNameID]       INT             NULL,
    [iSettlementTermsID]       INT             CONSTRAINT [DF_CLIENT_iSettlementTermsID] DEFAULT ((0)) NOT NULL,
    [bSourceDocPrint]          BIT             CONSTRAINT [DF_CLIENT_bSourceDocPrint] DEFAULT ((1)) NOT NULL,
    [bSourceDocEmail]          BIT             CONSTRAINT [DF_CLIENT_bSourceDocEmail] DEFAULT ((0)) NOT NULL,
    [iEUCountryID]             INT             CONSTRAINT [DF_Client_iEUCountryID] DEFAULT ((0)) NOT NULL,
    [iDefTaxTypeID]            INT             CONSTRAINT [DF_Client_iDefTaxTypeID] DEFAULT ((0)) NOT NULL,
    [bCODAccount]              BIT             CONSTRAINT [DF_Client_bCODAccount] DEFAULT ((0)) NOT NULL,
    [udARDate]                 DATETIME        NULL,
    [uiARDeliveryMethod]       INT             NULL,
    [tOrderNotes]              TEXT            CONSTRAINT [DF_Client_tOrderNotes_1] DEFAULT ('') NULL,
    [uiARCATID]                INT             NULL,
    [FuelLevyPercen]           DECIMAL (18, 2) CONSTRAINT [DF_Client_FuelLevyPercen] DEFAULT ((0)) NOT NULL,
    [FLID]                     INT             CONSTRAINT [DF_Client_FLID] DEFAULT ((0)) NOT NULL,
    [AccountStatusID]          INT             CONSTRAINT [DF_Client_AccountStatusID] DEFAULT ((1)) NOT NULL,
    [IGUFabRate]               FLOAT (53)      CONSTRAINT [DF_Client_IGUFabRate] DEFAULT ((0)) NOT NULL,
    [CreditPercentage]         FLOAT (53)      CONSTRAINT [DF_Client_CreditPercentage] DEFAULT ((0)) NOT NULL,
    [TotalDebitBalance]        FLOAT (53)      CONSTRAINT [DF_Client_TotalDebitBalance] DEFAULT ((0)) NOT NULL,
    [TotInvoiced]              FLOAT (53)      CONSTRAINT [DF_Client_TotInvoiced] DEFAULT ((0)) NOT NULL,
    [TotPending]               FLOAT (53)      CONSTRAINT [DF_Client_TotPending] DEFAULT ((0)) NOT NULL,
    [TotReceived]              FLOAT (53)      CONSTRAINT [DF_Client_TotReceived] DEFAULT ((0)) NOT NULL,
    [IsGlobalAcc]              BIT             CONSTRAINT [DF_Client_IsGlobalAcc] DEFAULT ((0)) NOT NULL,
    [IsProspect]               BIT             CONSTRAINT [DF_Client_IsProspect] DEFAULT ((0)) NOT NULL,
    [CardIdentification]       VARCHAR (50)    CONSTRAINT [DF_Client_CardIdentification] DEFAULT ('') NOT NULL,
    [LegalName]                VARCHAR (50)    NULL,
    [TrustName]                VARCHAR (50)    NULL,
    [BusinessEstablished]      SMALLDATETIME   NULL,
    [RegistrationNo]           VARCHAR (20)    CONSTRAINT [DF_Client_CardIdentification1] DEFAULT ('') NULL,
    [ACN]                      VARCHAR (20)    CONSTRAINT [DF_Client_RegistrationNo1_1] DEFAULT ('') NULL,
    [Token]                    VARCHAR (30)    CONSTRAINT [DF_Client_RegistrationNo1] DEFAULT ('') NULL,
    [EntityStructureID]        INT             CONSTRAINT [DF_Client_FLID1] DEFAULT ((0)) NOT NULL,
    [InsuredID]                INT             CONSTRAINT [DF_Client_EntityStructureID1] DEFAULT ((0)) NOT NULL,
    [CreditApplicationDate]    SMALLDATETIME   NULL,
    [PPS_ExpiryDate]           SMALLDATETIME   NULL,
    [PersonalGurantee]         VARCHAR (200)   NULL,
    [CC_NameOnCard]            VARCHAR (20)    NULL,
    [CC_CardNumber]            VARCHAR (16)    NULL,
    [CC_ExpiryDate]            SMALLDATETIME   NULL,
    [BSB]                      VARCHAR (6)     NULL,
    [AcountNumber]             VARCHAR (20)    NULL,
    [AcountName]               VARCHAR (20)    NULL,
    [CreditSearch]             SMALLDATETIME   NULL,
    [GONI]                     VARCHAR (20)    NULL,
    [bSendOrderConfirmations]  BIT             CONSTRAINT [DF_Client_bSendOrderConfirmations] DEFAULT ((0)) NOT NULL,
    [EmailOrderConfirmationTo] VARCHAR (200)   CONSTRAINT [DF_Client_EmailOrderConfirmationTo] DEFAULT ('') NOT NULL,
    [EmailTaxInvoicesTo]       VARCHAR (200)   CONSTRAINT [DF_Client_EmailOrderConfirmationTo1] DEFAULT ('') NOT NULL,
    [EmailStatementsTo]        VARCHAR (200)   CONSTRAINT [DF_Client_EmailOrderConfirmationTo2] DEFAULT ('') NOT NULL,
    [RebateID]                 INT             CONSTRAINT [DF_Client_RebateID] DEFAULT ((1)) NOT NULL,
    [XeroGUID]                 VARCHAR (50)    CONSTRAINT [DF_Client_XeroGUID] DEFAULT ('') NOT NULL,
    CONSTRAINT [PK_CLIENT] PRIMARY KEY CLUSTERED ([DCLink] ASC) WITH (FILLFACTOR = 90)
)