CREATE TABLE [dbo].[StkItem] (
    [StockLink]              INT           IDENTITY (1, 1) NOT NULL,
    [Code]                   VARCHAR (255) NULL,
    [Description_1]          VARCHAR (255) NULL,
    [Description_2]          VARCHAR (255) NULL,
    [Description_3]          VARCHAR (255) NULL,
    [ItemGroup]              VARCHAR (20)  NULL,
    [Pack]                   VARCHAR (5)   NULL,
    [TTI]                    VARCHAR (4)   NULL,
    [TTC]                    VARCHAR (4)   NULL,
    [TTG]                    VARCHAR (4)   NULL,
    [TTR]                    VARCHAR (4)   NULL,
    [Bar_Code]               VARCHAR (255) NULL,
    [Re_Ord_Lvl]             FLOAT (53)    NULL,
    [Re_Ord_Qty]             FLOAT (53)    NULL,
    [Min_Lvl]                FLOAT (53)    NULL,
    [Max_Lvl]                FLOAT (53)    NULL,
    [AveUCst]                FLOAT (53)    NULL,
    [LatUCst]                FLOAT (53)    NULL,
    [LowUCst]                FLOAT (53)    NULL,
    [HigUCst]                FLOAT (53)    NULL,
    [StdUCst]                FLOAT (53)    NULL,
    [Qty_On_Hand]            FLOAT (53)    NULL,
    [LGrvCount]              FLOAT (53)    NULL,
    [ServiceItem]            BIT           CONSTRAINT [DF__STKITEM__Service__290D0E62] DEFAULT ((0)) NOT NULL,
    [ItemActive]             BIT           CONSTRAINT [DF__STKITEM__ItemAct__2A01329B] DEFAULT ((1)) NOT NULL,
    [ReservedQty]            FLOAT (53)    NULL,
    [QtyOnPO]                FLOAT (53)    NULL,
    [QtyOnSO]                FLOAT (53)    NULL,
    [WhseItem]               BIT           CONSTRAINT [DF__STKITEM__WhseIte__2AF556D4] DEFAULT ((0)) NOT NULL,
    [SerialItem]             BIT           CONSTRAINT [DF__STKITEM__SerialI__2BE97B0D] DEFAULT ((0)) NOT NULL,
    [DuplicateSN]            BIT           CONSTRAINT [DF__STKITEM__Duplica__2CDD9F46] DEFAULT ((0)) NOT NULL,
    [StrictSN]               BIT           CONSTRAINT [DF__STKITEM__StrictS__2DD1C37F] DEFAULT ((0)) NOT NULL,
    [BomCode]                VARCHAR (1)   NULL,
    [SMtrxCol]               INT           NULL,
    [PMtrxCol]               INT           NULL,
    [JobQty]                 FLOAT (53)    NULL,
    [cModel]                 VARCHAR (50)  NULL,
    [cRevision]              VARCHAR (50)  NULL,
    [cComponent]             VARCHAR (50)  NULL,
    [dDateReleased]          SMALLDATETIME NULL,
    [iBinLocationID]         INT           NULL,
    [dStkitemTimeStamp]      DATETIME      NULL,
    [iInvSegValue1ID]        INT           NULL,
    [iInvSegValue2ID]        INT           NULL,
    [iInvSegValue3ID]        INT           NULL,
    [iInvSegValue4ID]        INT           NULL,
    [iInvSegValue5ID]        INT           NULL,
    [iInvSegValue6ID]        INT           NULL,
    [iInvSegValue7ID]        INT           NULL,
    [cExtDescription]        VARCHAR (255) NULL,
    [cSimpleCode]            VARCHAR (20)  NULL,
    [bCommissionItem]        BIT           CONSTRAINT [DF_StkItem_bCommissionItem] DEFAULT ((1)) NOT NULL,
    [MFPQty]                 FLOAT (53)    NULL,
    [bLotItem]               BIT           CONSTRAINT [DF_StkItem_bLotItem] DEFAULT ((0)) NOT NULL,
    [iLotStatus]             INT           NULL,
    [bLotMustExpire]         BIT           CONSTRAINT [DF_StkItem_bLotMustExpire] DEFAULT ((1)) NOT NULL,
    [iItemCostingMethod]     INT           CONSTRAINT [DF_StkItem_iItemCostingMethod] DEFAULT ((0)) NOT NULL,
    [fItemLastGRVCost]       FLOAT (53)    CONSTRAINT [DF_StkItem_fItemLastGRVCost] DEFAULT ((0)) NOT NULL,
    [iEUCommodityID]         INT           CONSTRAINT [DF_StkItem_iEUCommodityID] DEFAULT ((0)) NOT NULL,
    [iEUSupplementaryUnitID] INT           CONSTRAINT [DF_StkItem_iEUSupplementaryUnitID] DEFAULT ((0)) NOT NULL,
    [fNetMass]               FLOAT (53)    CONSTRAINT [DF_StkItem_fNetMass] DEFAULT ((0)) NOT NULL,
    [iUOMStockingUnitID]     INT           NULL,
    [iUOMDefPurchaseUnitID]  INT           NULL,
    [iUOMDefSellUnitID]      INT           NULL,
    [uiIISRVPRICEID]         INT           NULL,
    [ubIIEDGEALLOWANCE]      BIT           NULL,
    [ufIIThickness]          FLOAT (53)    NULL,
    [ubIITemplate]           BIT           NULL,
    [uiIITemplPriceID]       INT           NULL,
    [ubIIGLASSSERVICE]       BIT           NULL,
    [uiIIItemType]           INT           NULL,
    [ufIIMINCHRG]            FLOAT (53)    NULL,
    [ufIIMINSQM]             FLOAT (53)    NULL,
    [ufIIWEIGHT]             FLOAT (53)    NULL,
    [uiIIPRICETYPEID]        INT           NULL,
    [ubIIPrintLabels]        BIT           NULL,
    [DefaultGlassService]    BIT           CONSTRAINT [DF_StkItem_DefaultGlassService] DEFAULT ((0)) NOT NULL,
    [IsLaminateItem]         BIT           CONSTRAINT [DF_StkItem_IsLaminateItem_1] DEFAULT ((0)) NOT NULL,
    [ufIIQtyInVolume]        FLOAT (53)    NULL,
    [uiIIMainItemLink]       INT           NULL,
    [ubIIAllowNegative]      BIT           NULL,
    [uiIISupplier]           INT           NULL,
    [uiIIWidth]              INT           NULL,
    [uiIIHeight]             INT           NULL,
    [ufIILotQty]             FLOAT (53)    NULL,
    [ufIIGrvQty]             FLOAT (53)    NULL,
    [ufIISOQtyVolume]        FLOAT (53)    NULL,
    [uiIIWarehouse]          FLOAT (53)    NULL,
    [ShowPODes]              BIT           CONSTRAINT [DF_StkItem_ShowPODes] DEFAULT ((0)) NOT NULL,
    [IsNonStockItem]         BIT           CONSTRAINT [DF_StkItem_IsNonStockItem] DEFAULT ((0)) NOT NULL,
    [IsExternalItem]         BIT           CONSTRAINT [DF_StkItem_IsExternalItem] DEFAULT ((0)) NOT NULL,
    [POMinimumArea]          FLOAT (53)    CONSTRAINT [DF_StkItem_POMinimumArea] DEFAULT ((0)) NOT NULL,
    [AccountNumber]          VARCHAR (50)  CONSTRAINT [DF_StkItem_AccountNumber] DEFAULT ('') NOT NULL,
    [CostCentre]             INT           CONSTRAINT [DF_StkItem_CostCentre] DEFAULT ((0)) NOT NULL,
    [AddDetails]             VARCHAR (255) NULL,
    [SalesAccount]           VARCHAR (50)  NULL,
    [PurchaseAccount]        VARCHAR (50)  NULL,
    [Length]                 FLOAT (53)    NULL,
    [BulkQty]                FLOAT (53)    NULL,
    [BulkRate]               FLOAT (53)    NULL,
    [PriceListItem]          BIT           CONSTRAINT [DF_StkItem_PriceListItem] DEFAULT ((1)) NOT NULL,
    [CalcPriceAsPercentage]  BIT           CONSTRAINT [DF_StkItem_PriceListItem1] DEFAULT ((0)) NOT NULL,
    [CalcPricePercentage]    FLOAT (53)    CONSTRAINT [DF_StkItem_CalcPricePercentage] DEFAULT ((0)) NOT NULL,
    [BOMItem]                BIT           CONSTRAINT [DF_StkItem_BOMItem] DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_STKITEM] PRIMARY KEY CLUSTERED ([StockLink] ASC) WITH (FILLFACTOR = 90)
)